const data = [
  {
    projectGroupId: 23,
    metroAreaId: 1007,
    projectName: "Edgewater",
    productId: "980",
    productName: "The Davis",
  },
  {
    projectGroupId: 23,
    metroAreaId: 1007,
    projectName: "Edgewater",
    productId: "E15",
    productName: "The Amelia",
  },
  {
    projectGroupId: 23,
    metroAreaId: 1007,
    projectName: "Edgewater",
    productId: "Y54",
    productName: "The Lockwood",
  },
  {
    projectGroupId: 23,
    metroAreaId: 1007,
    projectName: "Edgewater",
    productId: "Y58",
    productName: "The Prescott",
  },
  {
    projectGroupId: 25,
    metroAreaId: 1007,
    projectName: "Inwood",
    productId: "1562",
    productName: "The Dupree",
  },
  {
    projectGroupId: 41,
    metroAreaId: 1008,
    projectName: "Estuary at Bowen Village",
    productId: "1601",
    productName: "The Stono",
  },
  {
    projectGroupId: 41,
    metroAreaId: 1008,
    projectName: "Estuary at Bowen Village",
    productId: "U68",
    productName: "The Moultrie",
  },
  {
    projectGroupId: 43,
    metroAreaId: 1008,
    projectName: "Mixson",
    productId: "1674",
    productName: "The Stella",
  },
  {
    projectGroupId: 47,
    metroAreaId: 1008,
    projectName: "Oldfield",
    productId: "1665",
    productName: "The Tidalview",
  },
  {
    projectGroupId: 47,
    metroAreaId: 1008,
    projectName: "Oldfield",
    productId: null,
    productName: null,
  },
];
